<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CodeRag.Application\CodeRag.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BlogDoFT.Libs.DapperUtils.Postgres" Version="1.12.0" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.19" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.19" />
    <PackageReference Include="Npgsql" Version="9.0.5" />
    <PackageReference Include="Pgvector" Version="0.3.2" />
    <PackageReference Include="Roslynator.Analyzers" Version="5.0.0" />
    <PackageReference Include="Roslynator.CodeFixes" Version="5.0.0" />
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="5.0.0" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.33.0.1635" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\stylecop.json" />
  </ItemGroup>

</Project>
