<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CodeRag.Embeddings.Abstraction\CodeRag.Embeddings.Abstraction.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BlogDoFT.Libs.ResultPattern" Version="1.10.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.19" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
